apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-projeto1-app-pv

spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
  - hard
  nfs:
    server: 192.168.0.50
    path: /mnt/data-persistent